config:
  type: OpenFOAM
  case:
    name: base
    type: submodule
    repo: https://develop.openfoam.com/committees/hpc.git

submodules:
  - name: ogl
    description: The main driver of this labbook, proving linear solver and preconditioner
    repo: https://github.com/hpsim/OGL.git
    run: |
      mkdir -p builds/dev
      cmake -G ${{env.OGL_MAKE_GENERATOR}} -B builds/dev -S . -DCMAKE_BUILD_TYPE=Release ${{env.OGL_CMAKE_FLAGS}}
      cmake --build ./builds/dev --config Release
      cmake --install ./builds/dev
  - name: obr
    description: Collection of python scripts to generate parameter studies
    repo: https://github.com/hpsim/OBR.git
    run: pip3 install -e . --user
  - name: ogl_plot_scripts
    description: A set of scripts to import and plot the perfomance data
    repo: https://github.com/hpsim/plot_ogl_data.git
    build-type: no-build

cases:
  - name: lidDrivenCavity3D_resolution
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.folder}}
    path: lidDrivenCavity
    matrix:
      - file: lidDrivenCavity3D_resolution.json
        folder: resolution
  - name: lidDrivenCavity3D_solver
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.folder}}
    path: lidDrivenCavity
    matrix:
      - file: lidDrivenCavity3D_solver.json
        folder: lidDrivenCavity3D
  - name: motorcycle_resolution
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.name}}
    path: motorcycle
    matrix:
      - file: motorcycle_resolution.json
        name: resolution
  - name: motorcycle_solver
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.name}}
    path: motorcycle
    matrix:
      - file: motorcycle_solver.json
        name: solver
  - name: motorcycle_fullRun
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.name}}
    path: motorcycle
    matrix:
      - file: motorcycle_full.json
        name: fullRun


pipelines:
  - name: decompose
    run: obr decompose --folder . --filter=mpiRank/40 --select=Multigrid
  - name: run_gko
    run: obr benchmark --folder . --select=${{env.GINKGO_EXECUTOR}}${{env.OBR_SELECT}} --filter=mpiRank/32 --report=GKO_${{env.HOSTNAME}}_${{env.GINKGO_EXECUTOR}}_${{env.OBR_SELECT}}.csv --results_folder=results --log_name=gko_${{env.HOSTNAME}}.log
    results:
      - results
  - name: run_of
    run: obr benchmark --folder . --select=DefaultOF${{env.OBR_SELECT}} --filter=mpiRank/8 --report=OF_${{env.HOSTNAME}${{env.OBR_SELECT}}.csv --results_folder=results --log_name=of_${{env.HOSTNAME}}.log
    results:
      - results

hooks:
  - on_rebase: ["create_cases"]
