config:
  type: OpenFOAM
  case:
    name: base
    type: submodule
    repo: https://develop.openfoam.com/committees/hpc.git

submodules:
  - name: ogl
    description: The main driver of this labbook, proving linear solver and preconditioner
    repo: https://github.com/hpsim/OGL.git
    run: |
      mkdir -p builds/dev
      cmake -G ${{env.OGL_MAKE_GENERATOR}} -B builds/dev -S . -DCMAKE_BUILD_TYPE=Release ${{env.OGL_CMAKE_FLAGS}}
      cmake --build ./builds/dev --config Release
      cmake --install ./builds/dev
  - name: obr
    description: Collection of python scripts to generate parameter studies
    repo: https://github.com/hpsim/OBR.git
    run: pip3 install -e . --user
  - name: ogl_plot_scripts
    description: A set of scripts to import and plot the perfomance data
    repo: https://github.com/hpsim/plot_ogl_data.git
    build-type: no-build

cases:
  - name: motorcycle
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/motorcycle/${{matrix.file}} --folder ${{matrix.name}} --filter ${{env.OBR_FILTER}}
    path: motorcycle_local
    matrix:
      - file: scaling.json
        folder: scaling
  - name: lidDrivenCavity
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/lidDrivenCavity3D/${{matrix.file}} --folder ${{matrix.folder}} --filter ${{env.OBR_FILTER}}
    path: lidDrivenCavity
    matrix:
      - file: scaling.json
        folder: scaling
  - name: lidDrivenCavity3D_tolerance
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.folder}}
    path: lidDrivenCavity
    matrix:
      - file: lidDrivenCavity3D_tolerance.json
        folder: tolerance
  - name: lidDrivenCavity3D_solver
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.folder}}
    path: lidDrivenCavity
    matrix:
      - file: lidDrivenCavity3D_solver.json
        folder: solver
  - name: motorcycle_resolution
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.name}}
    path: motorcycle
    matrix:
      - file: motorcycle_resolution.json
        name: resolution
  - name: motorcycle_solver
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.name}}
    path: motorcycle
    matrix:
      - file: motorcycle_solver.json
        name: solver
  - name: motorcycle_fullRun
    run: obr create --parameters ${{env.OGL_LABBOOK}}/assets/${{matrix.file}} --folder ${{matrix.name}}
    path: motorcycle
    matrix:
      - file: motorcycle_full.json
        name: fullRun


pipelines:
  - name: decompose
    run: obr decompose --folder . --select=${{env.OBR_SELECT}}
  - name: run_gpu
    run: obr benchmark --folder . --select=${{env.GINKGO_EXECUTOR}},${{env.OBR_SELECT}}  --report=gko_${{env.HOSTNAME}}_${{env.GINKGO_EXECUTOR}}_${{env.OBR_SELECT}}.csv --results_folder=results --log_name=gko_${{env.GINKGO_EXECUTOR}}_${{env.HOSTNAME}}.log
    results:
      - results
  - name: run_cpu
    run: obr benchmark --folder . --select=DefaultOF,${{env.OBR_SELECT}} --report=of_${{env.HOSTNAME}}_${{env.OBR_SELECT}}.csv --results_folder=results --log_name=of_DefaultOF_${{env.HOSTNAME}}.log
    results:
      - results
  - name: slurm_run_cpu
    run: obr benchmark --partition cpuonly --ntasks_per_node=${{env.NCORES}} --time 720 --select=DefaultOF,${{env.OBR_SELECT}} --folder . --runner SlurmCaseRunner --report=of_${{env.HOSTNAME}}_${{env.OBR_SELECT}}.csv --results_folder=results --log_name=of_${{env.HOSTNAME}}.log
    results:
      - results
  - name: slurm_run_gpu
    run: obr benchmark --partition accelerated --ntasks_per_node=${{env.NGPUS}} --time 720 --select=${{env.GINKGO_EXECUTOR}},${{env.OBR_SELECT}} --folder . --runner SlurmCaseRunner --report=gko_${{env.HOSTNAME}}_${{env.OBR_SELECT}}.csv --results_folder=results --log_name=of_${{env.GINKGO_EXECUTOR}}_${{env.HOSTNAME}}.log
    results:
      - results
  - name: collect
    run: obr benchmark --select=${{env.OBR_SELECT}} --folder . --runner ResultsCollector --report=of_${{env.HOSTNAME}}${{env.OBR_SELECT}}.csv --results_folder=results --log_name=of_${{env.HOSTNAME}}.log
    results:
      - results

hooks:
  - on_rebase: ["create_cases"]
